services:
    app.menu_builder:
        class: RJSite\FrontBundle\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

#    rj_site_front.example:
#        class: RJSite\FrontBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
