<?php

namespace RJSite\ContactBundle\Repository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends \Doctrine\ORM\EntityRepository
{
}
